name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release'
        required: true
        default: 'v1.3.2'

jobs:
  release:
    uses: stasher-dev/stasher-ci/.github/workflows/release.yml@main
    with:
      node-version: '20'
      build-command: 'npm run build'
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}